[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
ignore = [
    # Line too long: the formatter will handle this.
    "E501",
    # Conflicts with ruff formatter.
    "ISC001",
    # Mutable class attributes, a common pattern in Django.
    "RUF012",
]
select = [
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "C90",
    "DJ",
    "E",
    "ERA",
    "EXE",
    "F",
    "FA",
    "FLY",
    "G",
    "I",
    "INP",
    "INT",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PGH",
    "PIE",
    "PT",
    "PTH",
    "PYI",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLOT",
    "T10",
    "T20",
    "TCH",
    "UP",
    "W",
    "YTT",
]

[tool.ruff.lint.isort]
force-single-line = true
