# Generated by Django 6.0.dev20250206155744 on 2025-03-03 12:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="releasetrack",
            options={"ordering": ["release", "track_number"]},
        ),
        migrations.AlterField(
            model_name="releasetrack",
            name="track",
            field=models.ForeignKey(
                help_text="There may be multiple versions of a track with the same name.",
                on_delete=django.db.models.deletion.CASCADE,
                to="demo.track",
            ),
        ),
        migrations.AlterField(
            model_name="releasetrack",
            name="track_number",
            field=models.PositiveIntegerField(help_text="The first track is 1, not 0."),
        ),
    ]
